/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AContainer: typeof import('./src/components/container/AContainer.vue')['default']
    AInput: typeof import('./src/components/input/AInput.vue')['default']
    ASkeleton: typeof import('./src/components/skeleton/ASkeleton.vue')['default']
    AvailableCard: typeof import('./src/components/available-card/AvailableCard.vue')['default']
    ConnectionLine: typeof import('./src/components/connection-line/ConnectionLine.vue')['default']
    Container: typeof import('./src/components/container/Container.vue')['default']
    DataTable: typeof import('./src/components/available-card/dataTable.vue')['default']
    Input: typeof import('./src/components/input/Input.vue')['default']
    InputBox: typeof import('./src/components/input/InputBox.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
